### ISSUE TITLE
ComyUI Modern UX

### ISSUE THREAD

**Issue by manchuwook** [Tenney95/ComfyUI-NodeAligner#11]
First, thank you for the amazing custom_node!

It disappears when doing anything and won't load at all now.  ComfyAnonymous now has a docking menu.  Would you be able to leverage that to have a toolbar?

首先，谢谢你制作了这个很棒的custom_node！现在在做任何操作时都会消失，而且现在根本无法加载。ComfyAnonymous现在有一个停靠菜单。你能不能利用它来创建一个工具栏呢

![image](https://github.com/user-attachments/assets/5c41b72f-c9f6-4178-953f-30f843177a3c)

**Comment by w3c0929** [comment]
遇到了同样的问题，消失不见了

**Comment by LiJT** [comment]
同样，已经消失了在chrome中，但是在edge浏览器却能看到？非常奇怪的bug！

**Comment by manchuwook** [comment]
It doesn't appear in Edge either

**Comment by LiJT** [comment]
> It doesn't appear in Edge either

目前可以按F12打开控制台，找到应用程序（Application）下面的本地存储（Local storage）然后把里面的NodeAlignerButtonContainerPosition 删了, This works for me

**Comment by Tenney95** [comment]
之前遇到过，但是后来我做边缘控制了就没遇到过这情况了，复现不了bug不知道什么原因，可以右键它然后选择“选中后显示”，这样选中后他会在你鼠标附近出现。

I encountered this issue before, but after implementing edge controls, I haven't come across it again. I can't reproduce the bug and don't know the reason. You can right-click it and select 'Reveal Element,' which will make it appear near your mouse when selected.

**Comment by manchuwook** [comment]
I do not see "Reveal Element"

Per Copilot

To add a floating toolbar component that performs layout actions for node items in your front-end, you can follow these steps:

1. **Clone the NodeAligner Extension**: Clone the repository from the provided link to understand how it implements the floating toolbar.

2. **Understand the NodeAligner Implementation**: Review the code in the `ComfyUI-NodeAligner` repository to understand how it integrates the floating toolbar and performs layout actions.

3. **Integrate the Floating Toolbar**:
    - Create a new Vue component for the floating toolbar.
    - Implement methods for various layout actions (e.g., align left, align right, distribute evenly) within this component.
    - Add the toolbar component to your main layout or node item components.

4. **Add Event Listeners**: Ensure that the toolbar's buttons trigger the layout actions when clicked. You can use Vue's event system to handle these interactions.

5. **Style the Toolbar**: Apply CSS to position the toolbar as floating and ensure it has the desired look and feel.

6. **Test the Integration**: Thoroughly test the toolbar to ensure it performs the layout actions correctly without affecting other functionalities.

Here is a basic example to get you started on creating a floating toolbar component in Vue:

```vue
<template>
  <div class="floating-toolbar">
    <button @click="alignLeft">Align Left</button>
    <button @click="alignRight">Align Right</button>
    <button @click="distributeEvenly">Distribute Evenly</button>
  </div>
</template>

<script>
export default {
  methods: {
    alignLeft() {
      // Logic for aligning nodes to the left
    },
    alignRight() {
      // Logic for aligning nodes to the right
    },
    distributeEvenly() {
      // Logic for distributing nodes evenly
    }
  }
}
</script>

<style scoped>
.floating-toolbar {
  position: fixed;
  top: 10px;
  right: 10px;
  background: #fff;
  border: 1px solid #ccc;
  padding: 10px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}
</style>
```

You can expand on this template by adding more layout actions and refining the styling. Reviewing the `ComfyUI-NodeAligner` code will provide more specific details for your implementation.

To determine if the floating toolbar can support drag and drop integration similar to the dockable "Queue" toolbar component, I found the relevant files and components related to the "Queue" functionality:

- [QueueSidebarTab.vue](https://github.com/Comfy-Org/ComfyUI_frontend/blob/89bf5c182d396cd1c8d2e7c93e92639a47de4448/src/components/sidebar/tabs/QueueSidebarTab.vue)
- [queueSidebarTab.ts](https://github.com/Comfy-Org/ComfyUI_frontend/blob/89bf5c182d396cd1c8d2e7c93e92639a47de4448/src/hooks/sidebarTabs/queueSidebarTab.ts)
- [ComfyQueueButton.vue](https://github.com/Comfy-Org/ComfyUI_frontend/blob/89bf5c182d396cd1c8d2e7c93e92639a47de4448/src/components/actionbar/ComfyQueueButton.vue)

These components use Vue features and PrimeVue components to handle the UI interactions.

### Analysis
The "Queue" toolbar component utilizes PrimeVue components like `SplitButton`, `ButtonGroup`, and `ContextMenu` for interactive elements and manages states and events using Vue's reactive system.

### Recommendations
To implement similar drag and drop integration for your floating toolbar:
1. **Use PrimeVue Components**: Employ PrimeVue components for buttons and context menus.
2. **Add Drag and Drop Functionality**: Utilize Vue's drag and drop capabilities, potentially with libraries like `vue-drag-drop` or custom event handlers.
3. **Dockable Feature**: Implement docking by allowing the toolbar to be moved and snapped to predefined areas using CSS and JavaScript.

You can explore more components and their implementation [here](https://github.com/Comfy-Org/ComfyUI_frontend).

The relevant sections in the `QueueSidebarTab.vue` file for implementing drag and drop integration include:

1. **Template Section**: 
   - Handles button actions and layout.
   - `<template #tool-buttons>` section for toolbar buttons.
   - `<template #body>` for main content, including the task items grid.

2. **Script Section**: 
   - Imports necessary components and stores.
   - Defines methods such as `toggleExpanded`, `handleContextMenu`, `handlePreview`, `enterFolderView`, `exitFolderView`, and `toggleImageFit`.
   - Uses Vue's lifecycle hooks (`onMounted`, `onUnmounted`) and reactive properties (`ref`, `computed`).

3. **Style Section**: 
   - CSS for the scroll container and grid layout.

You can view more details [here](https://github.com/Comfy-Org/ComfyUI_frontend/blob/main/src/components/sidebar/tabs/QueueSidebarTab.vue).

Certainly! Here is an example implementation of the `alignCenter` function, which aligns a set of nodes to the center of their container. This example assumes that nodes are elements with a class of `node` and that they are contained within a parent element with a class of `nodes-container`.

### Updated FloatingToolbar.vue
```vue
<template>
  <div class="floating-toolbar">
    <button @click="alignLeft">Align Left</button>
    <button @click="alignRight">Align Right</button>
    <button @click="alignCenter">Align Center</button>
    <button @click="makeSameSize">Make Same Size</button>
    <button @click="distributeVertically">Distribute Vertically</button>
    <button @click="distributeHorizontally">Distribute Horizontally</button>
  </div>
</template>

<script>
export default {
  methods: {
    alignLeft() {
      // Logic for aligning selected nodes to the left
      console.log('Align Left action triggered');
    },
    alignRight() {
      // Logic for aligning selected nodes to the right
      console.log('Align Right action triggered');
    },
    alignCenter() {
      // Logic for centering selected nodes
      const nodesContainer = document.querySelector('.nodes-container');
      const nodes = document.querySelectorAll('.node');

      if (nodesContainer && nodes.length > 0) {
        const containerWidth = nodesContainer.clientWidth;
        nodes.forEach(node => {
          const nodeWidth = node.clientWidth;
          const leftPosition = (containerWidth - nodeWidth) / 2;
          node.style.position = 'absolute';
          node.style.left = `${leftPosition}px`;
        });
      }

      console.log('Align Center action triggered');
    },
    makeSameSize() {
      // Logic for making selected nodes the same size
      console.log('Make Same Size action triggered');
    },
    distributeVertically() {
      // Logic for distributing selected nodes vertically
      console.log('Distribute Vertically action triggered');
    },
    distributeHorizontally() {
      // Logic for distributing selected nodes horizontally
      console.log('Distribute Horizontally action triggered');
    }
  }
}
</script>

<style scoped>
.floating-toolbar {
  position: fixed;
  top: 10px;
  right: 10px;
  background: #fff;
  border: 1px solid #ccc;
  padding: 10px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  display: flex;
  flex-direction: column;
  gap: 5px;
}
button {
  padding: 5px 10px;
  cursor: pointer;
}
</style>
```

### Explanation

- **alignCenter Method**:
  - Selects the container (`nodes-container`) and all nodes (`node`).
  - Calculates the width of the container.
  - Iterates over each node, calculates the left position for centering, and sets the `left` CSS property.
  - Ensures the `position` style of nodes is set to `absolute` to enable positioning.

### Example Node Component (Node.vue)
```vue
<template>
  <div class="node" :style="nodeStyle">
    Node {{ id }}
  </div>
</template>

<script>
export default {
  props: {
    id: {
      type: Number,
      required: true
    }
  },
  computed: {
    nodeStyle() {
      return {
        width: '100px',
        height: '100px',
        border: '1px solid #000',
        margin: '10px'
      };
    }
  }
}
</script>

<style scoped>
.node {
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #fff; /* Default background color */
}
</style>
```

### Example Usage (Parent Component)
```vue
<template>
  <div>
    <FloatingToolbar />
    <div class="nodes-container" style="position: relative;">
      <Node v-for="id in nodeIds" :key="id" :id="id" />
    </div>
  </div>
</template>

<script>
import FloatingToolbar from './FloatingToolbar.vue';
import Node from './Node.vue';

export default {
  components: {
    FloatingToolbar,
    Node
  },
  data() {
    return {
      nodeIds: [1, 2, 3, 4, 5] // Example node IDs
    };
  }
}
</script>

<style scoped>
.nodes-container {
  position: relative; /* Ensure container is positioned relative for absolute positioned nodes */
  width: 100%; /* Set container width */
  height: 400px; /* Example container height */
  border: 1px solid #ccc; /* Example container border */
}
</style>
```

### Explanation
- **Parent Component**:
  - Includes the `FloatingToolbar` and `Node` components.
  - The `nodes-container` is styled with `position: relative` to allow absolute positioning of child nodes.
  - The `alignCenter` function is called when the "Align Center" button is clicked, centering all nodes within the container.

**Comment by manchuwook** [comment]
当然！以下是您的内容翻译成简体中文的版本，代码部分保持原样：

---

我没有看到 "Reveal Element"

根据 Copilot 的建议：

为了在您的前端添加一个执行节点项目布局操作的浮动工具栏组件，可以按照以下步骤进行：

1. **克隆 NodeAligner 扩展**：从提供的链接克隆仓库，以了解它是如何实现浮动工具栏的。

2. **理解 NodeAligner 的实现**：查看 `ComfyUI-NodeAligner` 仓库中的代码，了解它如何集成浮动工具栏并执行布局操作。

3. **集成浮动工具栏**：
   - 创建一个用于浮动工具栏的新 Vue 组件。
   - 在该组件中实现各种布局操作的方法（例如左对齐、右对齐、均匀分布）。
   - 将工具栏组件添加到主布局或节点项目组件中。

4. **添加事件监听器**：确保工具栏的按钮在点击时能够触发布局操作。可以使用 Vue 的事件系统来处理这些交互。

5. **样式化工具栏**：使用 CSS 将工具栏设置为浮动，并确保其具有理想的外观和布局。

6. **测试集成**：全面测试工具栏，以确保其正确执行布局操作，并且不会影响其他功能。

以下是一个用于创建浮动工具栏组件的基础示例：

```vue
<template>
  <div class="floating-toolbar">
    <button @click="alignLeft">Align Left</button>
    <button @click="alignRight">Align Right</button>
    <button @click="distributeEvenly">Distribute Evenly</button>
  </div>
</template>

<script>
export default {
  methods: {
    alignLeft() {
      // 节点左对齐逻辑
    },
    alignRight() {
      // 节点右对齐逻辑
    },
    distributeEvenly() {
      // 节点均匀分布逻辑
    }
  }
}
</script>

<style scoped>
.floating-toolbar {
  position: fixed;
  top: 10px;
  right: 10px;
  background: #fff;
  border: 1px solid #ccc;
  padding: 10px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}
</style>
```

您可以在此模板的基础上扩展功能，添加更多布局操作并优化样式。查看 `ComfyUI-NodeAligner` 的代码将为您的实现提供更多细节。

### 如何实现与 "Queue" 工具栏类似的拖放集成功能
通过查找相关文件，我发现与 "Queue" 功能相关的组件和文件包括：

- [[QueueSidebarTab.vue](https://github.com/Comfy-Org/ComfyUI_frontend/blob/89bf5c182d396cd1c8d2e7c93e92639a47de4448/src/components/sidebar/tabs/QueueSidebarTab.vue)](https://github.com/Comfy-Org/ComfyUI_frontend/blob/89bf5c182d396cd1c8d2e7c93e92639a47de4448/src/components/sidebar/tabs/QueueSidebarTab.vue)
- [[queueSidebarTab.ts](https://github.com/Comfy-Org/ComfyUI_frontend/blob/89bf5c182d396cd1c8d2e7c93e92639a47de4448/src/hooks/sidebarTabs/queueSidebarTab.ts)](https://github.com/Comfy-Org/ComfyUI_frontend/blob/89bf5c182d396cd1c8d2e7c93e92639a47de4448/src/hooks/sidebarTabs/queueSidebarTab.ts)
- [[ComfyQueueButton.vue](https://github.com/Comfy-Org/ComfyUI_frontend/blob/89bf5c182d396cd1c8d2e7c93e92639a47de4448/src/components/actionbar/ComfyQueueButton.vue)](https://github.com/Comfy-Org/ComfyUI_frontend/blob/89bf5c182d396cd1c8d2e7c93e92639a47de4448/src/components/actionbar/ComfyQueueButton.vue)

这些组件使用 Vue 特性和 PrimeVue 组件来处理 UI 交互。

### 分析
"Queue" 工具栏组件使用 PrimeVue 的组件（如 `SplitButton`、`ButtonGroup` 和 `ContextMenu`）来实现交互式元素，并通过 Vue 的响应式系统管理状态和事件。

### 建议
为了实现类似的拖放集成功能，可以：
1. **使用 PrimeVue 组件**：利用 PrimeVue 的按钮和上下文菜单组件。
2. **添加拖放功能**：使用 Vue 的拖放功能，可以选择使用诸如 `vue-drag-drop` 的库，或者编写自定义事件处理程序。
3. **实现可停靠特性**：允许工具栏被移动并通过 CSS 和 JavaScript 停靠到预定义区域。

您可以在 [[ComfyUI_frontend](https://github.com/Comfy-Org/ComfyUI_frontend)](https://github.com/Comfy-Org/ComfyUI_frontend) 中探索更多组件及其实现。

### 示例功能：`alignCenter`
以下是实现 `alignCenter` 功能的示例，它将一组节点对齐到容器的中心。假设节点是具有 `node` 类的元素，并包含在一个具有 `nodes-container` 类的父元素中。

#### 更新后的 FloatingToolbar.vue
```vue
<template>
  <div class="floating-toolbar">
    <button @click="alignLeft">Align Left</button>
    <button @click="alignRight">Align Right</button>
    <button @click="alignCenter">Align Center</button>
    <button @click="makeSameSize">Make Same Size</button>
    <button @click="distributeVertically">Distribute Vertically</button>
    <button @click="distributeHorizontally">Distribute Horizontally</button>
  </div>
</template>

<script>
export default {
  methods: {
    alignLeft() {
      console.log('Align Left action triggered');
    },
    alignRight() {
      console.log('Align Right action triggered');
    },
    alignCenter() {
      const nodesContainer = document.querySelector('.nodes-container');
      const nodes = document.querySelectorAll('.node');

      if (nodesContainer && nodes.length > 0) {
        const containerWidth = nodesContainer.clientWidth;
        nodes.forEach(node => {
          const nodeWidth = node.clientWidth;
          const leftPosition = (containerWidth - nodeWidth) / 2;
          node.style.position = 'absolute';
          node.style.left = `${leftPosition}px`;
        });
      }

      console.log('Align Center action triggered');
    },
    makeSameSize() {
      console.log('Make Same Size action triggered');
    },
    distributeVertically() {
      console.log('Distribute Vertically action triggered');
    },
    distributeHorizontally() {
      console.log('Distribute Horizontally action triggered');
    }
  }
}
</script>

<style scoped>
.floating-toolbar {
  position: fixed;
  top: 10px;
  right: 10px;
  background: #fff;
  border: 1px solid #ccc;
  padding: 10px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  display: flex;
  flex-direction: column;
  gap: 5px;
}
button {
  padding: 5px 10px;
  cursor: pointer;
}
</style>
```

---

以上翻译和示例代码供您参考，如果需要进一步帮助，请随时告诉我！

**Comment by Tenney95** [comment]
https://github.com/user-attachments/assets/ae6b65b6-0e5c-4b3a-aa36-237db8fbd0d3

This is recommended for convenience

**Comment by manchuwook** [comment]
https://github.com/user-attachments/assets/43ba91f7-e6c7-4c69-ba9d-fcf0c186fce8

The bar does not appear at all in Edge but is visible in Chrome.  In Chrome, it does not reposition to the cursor, it is stuck in the upper right.

It looks like 2 positional properties are "unset"

**Comment by manchuwook** [comment]
The toolbar not appearing could be caused by:

1. **Incorrect positioning logic**: The `setPosition` function might not be calculating or applying the correct position.
2. **Improper display logic**: The toolbar is hidden (`display: none`) or not shown when nodes are selected.

Here’s how we can address these issues.

---

### Adjust `setPosition` Method
Ensure the toolbar correctly positions itself under the selected nodes.

```javascript
setPosition(x, y) {
    // Ensure the toolbar remains within screen bounds
    const toolbarWidth = this.buttonContainer.offsetWidth;
    const toolbarHeight = this.buttonContainer.offsetHeight;
    const windowWidth = window.innerWidth;
    const windowHeight = window.innerHeight;

    // Adjust position to stay on screen
    if (x + toolbarWidth > windowWidth) {
        x = windowWidth - toolbarWidth - 10; // Add some padding
    }
    if (y + toolbarHeight > windowHeight) {
        y = windowHeight - toolbarHeight - 10; // Add some padding
    }

    // Apply the new position
    this.buttonContainer.style.left = `${x}px`;
    this.buttonContainer.style.top = `${y}px`;
}
```

---

### Update Node Selection Logic
Check the `pollForCanvas` method to ensure the toolbar shows up when nodes are selected.

1. Modify the click handler to accurately determine when nodes are selected and position the toolbar accordingly.

```javascript
pollForCanvas() {
    const canvas = document.querySelector('canvas#graph-canvas');
    if (canvas) {
        ButtonManager.init();

        // Listen for click events to handle node selection
        canvas.addEventListener('click', (event) => {
            const selectedNodes = ButtonManager.getSelectedNodes();

            if (selectedNodes.length > 0) {
                // Show and position toolbar under selected nodes
                ButtonManager.show();

                // Position toolbar under the last selected node
                const lastNode = selectedNodes[selectedNodes.length - 1];
                const nodeX = lastNode.pos[0];
                const nodeY = lastNode.pos[1] + lastNode.size[1]; // Position below the node

                // Use the calculated position
                ButtonManager.setPosition(nodeX, nodeY);
            } else {
                // Hide toolbar if no nodes are selected
                ButtonManager.hide();
            }
        });
    } else {
        setTimeout(pollForCanvas, 1000); // Retry after 1 second if the canvas isn't found
    }
}
```

---

### Debugging Steps
1. **Inspect Toolbar in DOM**:
   - Open the developer console and ensure the `#alignment-buttons` element is in the DOM.
   - Check its `display` and `position` styles to ensure it’s visible and positioned correctly.
   
2. **Verify Node Selection**:
   - Add a console log in `getSelectedNodes()` to check whether nodes are being correctly identified as selected.

   ```javascript
   getSelectedNodes() {
       const selectedNodesObj = LGraphCanvas.active_canvas.selected_nodes;
       console.log('Selected nodes:', selectedNodesObj);
       return selectedNodesObj ? Object.values(selectedNodesObj) : [];
   }
   ```

3. **Simulate Toolbar Placement**:
   - Manually set the toolbar position in the developer console to confirm it renders as expected.

   ```javascript
   ButtonManager.setPosition(100, 100); // Replace with any coordinates
   ButtonManager.show();
   ```

---

### Expected Behavior
After implementing these changes:
1. The toolbar should appear under the last selected node.
2. If no nodes are selected, the toolbar should remain hidden.
3. The toolbar should remain on screen and not overflow beyond the visible area.

Let me know how it goes or if further adjustments are needed!

**Comment by Tenney95** [comment]
ok,ok. I will look into it and see how to fix it. I haven't encountered this bug before.

**Comment by manchuwook** [comment]
This is much appreciated!  Thank you for your blood, sweat, and tears. 辛苦了 ❤️

**Comment by Tenney95** [comment]
I updated to a new version, and it's working well now. The issue didn't occur; it might have been related to a problem with localStorage.

**Comment by manchuwook** [comment]
It appears near the cursor when I release the button for the click in this one
![image](https://github.com/user-attachments/assets/04433b53-9ff1-4de9-81d2-b19607e7cb68)

But it is good enough for me.
