### ISSUE TITLE
1. 重复点击任意按钮导致面板向右移动 2. 途中情况莫名其妙无法左右对齐？

### ISSUE THREAD

**Issue by LiJT** [Tenney95/ComfyUI-NodeAligner#12]
![PixPin_2024-12-16_19-27-30](https://github.com/user-attachments/assets/abd426d5-e15d-43cb-86a3-f76f8642759c)

请查明

并且我看到

> 目前可以按F12打开控制台，找到应用程序（Application）下面的本地存储（Local storage）然后把里面的NodeAlignerButtonContainerPosition删了

这个方法好像不是那么优雅，最好是能有个独立的菜单
大佬辛苦，请先解决我提出的前两个bug吧，感谢！

**Comment by Tenney95** [comment]
我这不复现，约个时间方便远程看看嘛？
