### ISSUE TITLE
【视频】诡异的移动问题依然存在，反复点击按钮会造成面板移动，同时对齐按钮90%的情况下失灵无法进行对齐

### ISSUE THREAD

**Issue by LiJT** [Tenney95/ComfyUI-NodeAligner#13]
https://github.com/user-attachments/assets/c91dfb5c-24f3-4144-9230-9827b5e98e5a

大佬请看VCR...
还是那两个问题，我已经安装了最新版本的了，而且也按照指示打开控制台，找到应用程序（Application）下面的本地存储（Local storage）然后把里面的NodeAlignerButtonContainerPosition删了。还是这样会出现这样的问题

1. 面板会随着多次按下按钮产生微小的左右移动
2. 经常性的对齐失灵，根本无反应，只有在重新框选节点后，偶尔（概率10%）的时候才能正确对齐，视频中有展示

使用环境：
Chrome最新版，Windows 10最新版

**Comment by Tenney95** [comment]
ok, ok，知道了，我去调调

**Comment by Tenney95** [comment]
对齐修改好了，优化了一下分组算法，然后每次点击往下移动那个还没找到问题，也没啥影响一般都点一下就完事了

**Comment by LiJT** [comment]
> 对齐修改好了，优化了一下分组算法，然后每次点击往下移动那个还没找到问题，也没啥影响一般都点一下就完事了

经过测试，已经修复好了！感谢大佬！！！
